services:
  - type: web
    name: disaster-med-backend-en
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_PASS
        value: disaster2026!
      - key: ADMIN_SECRET
        value: sch-disaster-med-admin-secret-key
    plan: free
